export const SIGN_IN_EMAIL = 'SIGN_IN_EMAIL';
export const SIGN_IN_EMAIL_SUCCESS = 'SIGN_IN_EMAIL_SUCCESS';
export const SIGN_IN_EMAIL_FAILED = 'SIGN_IN_EMAIL_FAILED';
export const REGISTER_IN_EMAIL = 'REGISTER_IN_EMAIL';
export const REGISTER_IN_EMAIL_SUCCESS = 'REGISTER_IN_EMAIL_SUCCESS';
export const REGISTER_IN_EMAIL_FAILED = 'REGISTER_IN_EMAIL_FAILED';
